/**
 * Enrich placeholder modules with real educational content
 * Run: node scripts/enrich-modules.js
 */
const fs = require('fs');
const p = require('path');
const LDIR = p.join(__dirname, '..', 'lessons');

function enrich(modIdx, lessonsContent) {
  const fp = p.join(LDIR, 'mod-' + modIdx + '.json');
  const mod = JSON.parse(fs.readFileSync(fp, 'utf8'));
  lessonsContent.forEach((lc, i) => {
    if (mod.lessons[i]) {
      mod.lessons[i].content = lc.content;
      if (lc.quiz) mod.lessons[i].quiz = lc.quiz;
    }
  });
  fs.writeFileSync(fp, JSON.stringify(mod));
  console.log('  ✓ mod-' + modIdx + ': ' + mod.title);
}

// Also update index.json quizzes
function updateIndex(modIdx, lessonsQuiz) {
  const idxPath = p.join(LDIR, 'index.json');
  const idx = JSON.parse(fs.readFileSync(idxPath, 'utf8'));
  lessonsQuiz.forEach((lq, i) => {
    if (idx[modIdx] && idx[modIdx].lessons[i] && lq.quiz) {
      idx[modIdx].lessons[i].quiz = lq.quiz;
    }
  });
  fs.writeFileSync(idxPath, JSON.stringify(idx));
}

console.log('Enriching modules with real educational content...\n');

// ========================
// MOD 46: Fake News e Fact-Checking
// ========================
enrich(46, [
  {content:'<h3>O que São Fake News?</h3><p><strong>Fake news</strong> são informações falsas criadas e espalhadas deliberadamente para enganar. Diferente de um erro jornalístico (que é corrigido), fake news são intencionais.</p><p>Tipos principais: <em>desinformação</em> (falso, criado para enganar), <em>misinformação</em> (falso, compartilhado sem saber) e <em>malinformação</em> (verdadeiro, mas usado fora de contexto para prejudicar).</p><p>Em 2016, as 20 fake news mais compartilhadas no Facebook tiveram <strong>mais engajamento</strong> que as 20 notícias reais mais compartilhadas. O problema é sério: fake news se espalham 6x mais rápido que notícias verdadeiras (MIT, 2018).</p>',quiz:{q:'Qual a diferença entre desinformação e misinformação?',o:['São a mesma coisa','Desinformação é intencional, misinformação não','Misinformação é pior','Desinformação só existe online'],c:1,exp:'Desinformação é falsa E intencional (criada para enganar). Misinformação é falsa mas compartilhada sem saber que é falsa. A intenção é o que diferencia.'}},
  {content:'<h3>Viés Algorítmico</h3><p>Algoritmos de redes sociais mostram conteúdo que gera <strong>engajamento</strong> — e conteúdo falso, polêmico ou emocional gera mais cliques que a verdade.</p><p>O resultado: você vê mais do que já concorda (viés de confirmação amplificado), notícias sensacionalistas ganham destaque, e fontes sérias perdem alcance.</p><p>O YouTube, por exemplo, já recomendou vídeos conspiratórios 70% das vezes para quem assistiu um vídeo de ciência. O algoritmo não sabe o que é verdade — só sabe o que prende sua atenção.</p>',quiz:{q:'Por que algoritmos tendem a amplificar fake news?',o:['Porque são programados para mentir','Porque conteúdo falso/polêmico gera mais engajamento','Porque empresas de tech são desonestas','Porque a verdade é sempre chata'],c:1,exp:'Algoritmos otimizam para engajamento (cliques, tempo na tela). Conteúdo falso e emocional gera mais reações que fatos sóbrios, então é naturalmente amplificado.'}},
  {content:'<h3>Como Verificar uma Notícia</h3><p>O método SIFT (criado por Mike Caulfield) é simples e eficaz:</p><ul><li><strong>S</strong>top — Pare antes de compartilhar</li><li><strong>I</strong>nvestigate the source — Quem publicou? É confiável?</li><li><strong>F</strong>ind better coverage — Outros veículos estão noticiando?</li><li><strong>T</strong>race claims — Volte à fonte original do dado</li></ul><p>Regra de ouro: se uma notícia parece inacreditável demais (boa ou ruim), provavelmente é. A verdade raramente é tão dramática quanto fake news.</p>',quiz:{q:'O que significa o "F" no método SIFT?',o:['Find the author','Follow the money','Find better coverage (buscar outras fontes)','Forget and move on'],c:2,exp:'F = Find better coverage: verifique se outros veículos confiáveis estão reportando a mesma notícia. Se só uma fonte obscura publicou, desconfie.'}},
  {content:'<h3>Fontes Confiáveis vs Duvidosas</h3><p>Sinais de fonte confiável: autoria clara, data de publicação, links para fontes originais, correções publicadas, editorial transparente.</p><p>Sinais de fonte duvidosa: sem autor, sem data, títulos sensacionalistas ("URGENTE!", "VOCÊ NÃO VAI ACREDITAR"), sem fontes citadas, domínio estranho (.blog, .info, sites imitando portais reais).</p><p>Atenção: até fontes confiáveis cometem erros. A diferença é que elas <em>corrigem</em>. Nenhuma fonte é 100% imparcial — todas têm viés editorial. O ideal é consultar <strong>múltiplas fontes</strong> de perspectivas diferentes.</p>',quiz:{q:'Qual é um sinal de fonte duvidosa?',o:['Ter autoria clara','Publicar correções','Usar títulos sensacionalistas sem fontes','Ter CNPJ'],c:2,exp:'Títulos sensacionalistas ("URGENTE!", "CHOCANTE!") sem fontes citadas são bandeira vermelha. Fontes sérias usam títulos informativos e citam de onde tiraram os dados.'}},
  {content:'<h3>Imagens Manipuladas</h3><p>Fotos podem ser alteradas, cortadas, tiradas de contexto ou geradas por IA. Ferramentas para verificar:</p><ul><li><strong>Google Reverse Image Search</strong> — arraste a imagem para ver onde mais aparece</li><li><strong>TinEye</strong> — busca reversa de imagens</li><li><strong>Metadados (EXIF)</strong> — mostram data, câmera e local da foto original</li></ul><p>Exemplo clássico: foto de multidão no Egito em 2013 foi usada como "prova" de manifestação no Brasil. Mesma foto, contexto completamente diferente. Busca reversa revelou a fraude em segundos.</p>',quiz:{q:'Como verificar se uma foto é real ou manipulada?',o:['Confiar se parece real','Fazer busca reversa de imagem no Google','Verificar curtidas','Perguntar nos comentários'],c:1,exp:'Busca reversa de imagem (Google Images, TinEye) mostra onde mais a foto aparece, revelando se foi tirada de contexto, é antiga, ou é de outro lugar.'}},
  {content:'<h3>Deepfakes e IA</h3><p><strong>Deepfakes</strong> são vídeos ou áudios gerados por IA que colocam o rosto/voz de uma pessoa em conteúdo que ela nunca criou. A tecnologia avança rápido — em 2024, deepfakes são quase indistinguíveis do real.</p><p>Riscos: políticos "dizendo" coisas que nunca disseram, golpes financeiros com voz clonada, pornografia não-consensual, evidências falsificadas.</p><p>Como detectar (por enquanto): movimentos labiais ligeiramente descoordenados, bordas do rosto borradas, iluminação inconsistente. Mas a melhor defesa é <em>contexto</em>: se um vídeo parece absurdo, verifique a fonte.</p>',quiz:{q:'O que são deepfakes?',o:['Notícias falsas em texto','Vídeos/áudios gerados por IA que imitam pessoas reais','Perfis falsos em redes sociais','Vírus de computador'],c:1,exp:'Deepfakes usam IA para criar vídeos/áudios realistas de pessoas dizendo ou fazendo coisas que nunca fizeram. A tecnologia melhora rapidamente, tornando detecção cada vez mais difícil.'}},
  {content:'<h3>Clickbait e Sensacionalismo</h3><p><strong>Clickbait</strong> (isca de clique) é um título projetado para gerar curiosidade irresistível: "Você NÃO vai acreditar no que aconteceu!", "Médicos estão CHOCADOS com este truque!".</p><p>O problema: o conteúdo raramente entrega o que o título promete. Mas o clique já foi dado — e o site já ganhou com publicidade.</p><p>Sensacionalismo vai além: exagera fatos, omite contexto, usa emoção em vez de informação. A regra é simples: quanto mais dramático o título, mais ceticismo você deve ter.</p>',quiz:{q:'Qual o objetivo principal do clickbait?',o:['Informar o público','Gerar cliques para receita de publicidade','Alertar sobre perigos','Entreter'],c:1,exp:'Clickbait existe para gerar cliques, que geram receita de publicidade. O conteúdo é secundário — o que importa é que você clicou. Sites sérios não precisam de truques para atrair leitores.'}},
  {content:'<h3>Teorias Conspiratórias</h3><p>Teorias conspiratórias explicam eventos complexos através de um grupo secreto e poderoso agindo nas sombras. São atraentes porque oferecem explicações <em>simples</em> para problemas <em>complexos</em>.</p><p>Características: infalsificáveis (toda evidência contra é "parte da conspiração"), desconfiam de toda autoridade, conectam eventos não relacionados, e se espalham em comunidades fechadas.</p><p>Nem toda desconfiança é irracional — conspirações reais existem (Watergate, espionagem da NSA). A diferença: conspirações reais são descobertas por jornalismo e evidências, não por vídeos no YouTube sem fontes.</p>',quiz:{q:'O que torna uma teoria conspiratória difícil de refutar?',o:['Ter muitas evidências','Ser infalsificável — toda evidência contra é vista como parte da conspiração','Ser publicada em jornais','Ter base científica'],c:1,exp:'Teorias conspiratórias são infalsificáveis: se você apresenta evidência contra, dizem que "isso prova a conspiração". Ciência real aceita ser refutada — conspirações nunca aceitam.'}},
  {content:'<h3>Checagem de Fatos na Prática</h3><p>Organizações de fact-checking verificam declarações públicas e conteúdos virais. No Brasil: <strong>Aos Fatos</strong>, <strong>Lupa</strong>, <strong>Estadão Verifica</strong>, <strong>Fato ou Fake (G1)</strong>.</p><p>Internacionais: <strong>Snopes</strong>, <strong>PolitiFact</strong>, <strong>Full Fact</strong>, <strong>AFP Fact Check</strong>.</p><p>Exercício prático: pegue a última notícia que você compartilhou no WhatsApp. Busque no Google: "[trecho da notícia] + é verdade" ou "[trecho] + fake". Se nenhum veículo sério confirmou, não compartilhe.</p>',quiz:{q:'Qual dessas é uma agência de fact-checking brasileira?',o:['CNN','Aos Fatos','Wikipedia','Google'],c:1,exp:'Aos Fatos é uma das principais agências de fact-checking do Brasil, junto com Lupa e Estadão Verifica. Elas verificam declarações públicas e conteúdos virais usando metodologia jornalística.'}},
  {content:'<h3>Cidadão Digital Responsável</h3><p>Você é parte do problema ou da solução. Cada vez que compartilha algo sem verificar, contribui para a desinformação. Regras para ser um cidadão digital responsável:</p><ul><li><strong>Leia além do título</strong> — o artigo pode dizer o oposto</li><li><strong>Verifique antes de compartilhar</strong> — 30 segundos de checagem</li><li><strong>Diversifique suas fontes</strong> — saia da bolha</li><li><strong>Admita quando estiver errado</strong> — mudar de opinião é sinal de inteligência</li></ul><p>A democracia depende de cidadãos informados. Fake news corroem a confiança nas instituições, na ciência e uns nos outros. Sua responsabilidade digital importa.</p>',quiz:{q:'Qual a ação mais importante contra fake news que você pode tomar?',o:['Deletar redes sociais','Verificar antes de compartilhar','Confiar apenas em um jornal','Ignorar todas as notícias'],c:1,exp:'Verificar antes de compartilhar é a ação mais impactante. Se cada pessoa checasse uma notícia antes de repassar, o alcance de fake news cairia drasticamente.'}}
]);
updateIndex(46, [{quiz:{q:'Qual a diferença entre desinformação e misinformação?',o:['São a mesma coisa','Desinformação é intencional, misinformação não','Misinformação é pior','Desinformação só existe online'],c:1,exp:'Desinformação é falsa E intencional. Misinformação é falsa mas compartilhada sem saber.'}},{quiz:{q:'Por que algoritmos amplificam fake news?',o:['São programados para mentir','Conteúdo falso gera mais engajamento','Tech são desonestas','Verdade é chata'],c:1,exp:'Algoritmos otimizam engajamento, e conteúdo falso/emocional gera mais reações.'}},{quiz:{q:'O que significa "F" no método SIFT?',o:['Find the author','Follow the money','Find better coverage','Forget'],c:2,exp:'Find better coverage: buscar outras fontes confiáveis reportando a mesma notícia.'}},{quiz:{q:'Sinal de fonte duvidosa?',o:['Autoria clara','Correções publicadas','Títulos sensacionalistas sem fontes','Ter CNPJ'],c:2,exp:'Títulos sensacionalistas sem fontes são bandeira vermelha.'}},{quiz:{q:'Como verificar uma foto?',o:['Confiar se parece real','Busca reversa no Google','Verificar curtidas','Perguntar nos comentários'],c:1,exp:'Busca reversa revela onde mais a foto aparece.'}},{quiz:{q:'O que são deepfakes?',o:['Notícias falsas','Vídeos/áudios gerados por IA imitando pessoas','Perfis falsos','Vírus'],c:1,exp:'Deepfakes usam IA para criar vídeos realistas de pessoas.'}},{quiz:{q:'Objetivo do clickbait?',o:['Informar','Gerar cliques para publicidade','Alertar','Entreter'],c:1,exp:'Clickbait gera cliques para receita publicitária.'}},{quiz:{q:'O que torna conspiração difícil de refutar?',o:['Muitas evidências','É infalsificável','Publicada em jornais','Base científica'],c:1,exp:'Teorias conspiratórias são infalsificáveis.'}},{quiz:{q:'Agência de fact-checking brasileira?',o:['CNN','Aos Fatos','Wikipedia','Google'],c:1,exp:'Aos Fatos é uma das principais agências brasileiras.'}},{quiz:{q:'Ação mais importante contra fake news?',o:['Deletar redes','Verificar antes de compartilhar','Confiar em um jornal','Ignorar notícias'],c:1,exp:'Verificar antes de compartilhar é a ação mais impactante.'}}]);

// ========================
// MOD 52: Lógica de Programação
// ========================
enrich(52, [
  {content:'<h3>O que é Programação?</h3><p>Programação é dar <strong>instruções precisas</strong> para um computador executar. Diferente de humanos, computadores fazem EXATAMENTE o que você manda — nem mais, nem menos.</p><p>Tudo que você usa é software: Instagram, WhatsApp, jogos, Netflix. Alguém escreveu cada linha de código que faz essas coisas funcionarem.</p><p>Programação não é sobre decorar comandos — é sobre <strong>resolver problemas</strong> e <strong>pensar logicamente</strong>. É como aprender a pensar de um jeito novo.</p>',quiz:{q:'O que é programação?',o:['Usar computador','Dar instruções precisas para computadores executarem','Consertar hardware','Navegar na internet'],c:1,exp:'Programação é escrever instruções (código) que computadores executam. O computador faz exatamente o que é instruído — por isso precisão é fundamental.'}},
  {content:'<h3>Algoritmos do Dia a Dia</h3><p>Um <strong>algoritmo</strong> é uma sequência de passos para resolver um problema. Você já usa algoritmos sem saber:</p><ul><li>Receita de bolo = algoritmo culinário</li><li>GPS calculando rota = algoritmo de caminho</li><li>Seu método de estudo = algoritmo de aprendizado</li></ul><p>Todo algoritmo tem: <strong>entrada</strong> (ingredientes), <strong>processamento</strong> (passos) e <strong>saída</strong> (bolo pronto). Programar é traduzir esses passos para uma linguagem que o computador entende.</p>',quiz:{q:'O que é um algoritmo?',o:['Um tipo de computador','Uma sequência de passos para resolver um problema','Uma linguagem de programação','Um aplicativo'],c:1,exp:'Algoritmo é uma sequência finita de passos bem definidos para resolver um problema. Receitas, rotas e métodos de estudo são todos algoritmos.'}},
  {content:'<h3>Variáveis e Tipos</h3><p>Uma <strong>variável</strong> é uma caixa com nome onde guardamos informações. Exemplos:</p><pre><code>nome = "Maria"     (texto/string)\nidade = 14          (número inteiro)\naltura = 1.65       (número decimal)\nmaior = true        (verdadeiro/falso)</code></pre><p>Tipos principais: <strong>string</strong> (texto), <strong>int</strong> (inteiro), <strong>float</strong> (decimal), <strong>boolean</strong> (verdadeiro/falso). O tipo define o que você pode fazer — somar números faz sentido, somar nomes não.</p>',quiz:{q:'O que é uma variável em programação?',o:['Um tipo de erro','Um espaço na memória que armazena um valor com nome','Um comando de repetição','Uma função matemática'],c:1,exp:'Variável é um espaço na memória com um nome que armazena um valor. Como uma caixa etiquetada: você pode guardar, ler e alterar o conteúdo.'}},
  {content:'<h3>Condicionais (Se/Então)</h3><p>Condicionais permitem que o programa tome <strong>decisões</strong>:</p><pre><code>SE idade >= 18:\n    mostrar("Pode votar")\nSENÃO:\n    mostrar("Ainda não pode votar")</code></pre><p>A vida é cheia de condicionais: SE chover → leve guarda-chuva. SE nota >= 7 → aprovado. O computador avalia a condição e executa o bloco correto.</p><p>Condicionais podem ser encadeadas: SE... SENÃO SE... SENÃO. Isso permite decisões complexas com múltiplas opções.</p>',quiz:{q:'O que faz uma condicional (SE/ENTÃO)?',o:['Repete um código','Permite ao programa tomar decisões','Cria variáveis','Desenha na tela'],c:1,exp:'Condicionais permitem que o programa escolha entre caminhos diferentes baseado em uma condição. SE a condição for verdadeira, executa um bloco; SENÃO, executa outro.'}},
  {content:'<h3>Loops (Repetição)</h3><p><strong>Loops</strong> repetem um bloco de código várias vezes. Sem loops, programas seriam enormes e repetitivos.</p><pre><code>PARA i DE 1 ATÉ 10:\n    mostrar(i)\n\nENQUANTO saldo > 0:\n    fazer_compra()</code></pre><p>Dois tipos principais: <strong>PARA</strong> (quando sabe quantas vezes repetir) e <strong>ENQUANTO</strong> (quando repete até uma condição mudar). Todo jogo usa loops — o loop principal roda 60 vezes por segundo atualizando a tela!</p>',quiz:{q:'Quando usar "ENQUANTO" em vez de "PARA"?',o:['Nunca','Quando não sabe quantas vezes vai repetir','Quando quer repetir exatamente 10 vezes','Quando quer parar o programa'],c:1,exp:'Use ENQUANTO quando não sabe quantas repetições serão necessárias — o loop continua até a condição se tornar falsa. Use PARA quando sabe o número exato.'}},
  {content:'<h3>Funções</h3><p>Uma <strong>função</strong> é um bloco de código reutilizável com nome. Em vez de escrever o mesmo código várias vezes, você define uma função e a chama quando precisar:</p><pre><code>FUNÇÃO calcular_media(nota1, nota2):\n    soma = nota1 + nota2\n    RETORNAR soma / 2\n\nresultado = calcular_media(8, 7)  → 7.5</code></pre><p>Funções tornam o código: mais <strong>organizado</strong> (cada função faz uma coisa), mais <strong>legível</strong> (nomes descritivos) e mais <strong>reutilizável</strong> (use quantas vezes quiser).</p>',quiz:{q:'Qual a principal vantagem de usar funções?',o:['O programa fica mais rápido','Permite reutilizar código sem repetir','Ocupa menos memória','É obrigatório'],c:1,exp:'Funções permitem escrever código uma vez e reutilizar quantas vezes precisar. Isso torna o programa mais organizado, legível e fácil de manter.'}},
  {content:'<h3>Arrays e Listas</h3><p>Uma <strong>lista</strong> (ou array) guarda múltiplos valores em uma única variável:</p><pre><code>notas = [8.5, 7.0, 9.2, 6.8, 8.0]\nalunos = ["Ana", "Pedro", "Maria"]\n\nnotas[0]  → 8.5  (primeiro elemento)\nnotas[2]  → 9.2  (terceiro elemento)</code></pre><p>Índices começam em <strong>0</strong> (não em 1!). Isso confunde iniciantes mas é padrão em quase todas as linguagens. Listas são essenciais — sem elas, como armazenaria 1000 notas de alunos?</p>',quiz:{q:'Em uma lista, qual é o índice do PRIMEIRO elemento?',o:['1','0','-1','Depende da linguagem'],c:1,exp:'Na maioria das linguagens de programação, o primeiro elemento de uma lista tem índice 0 (zero-based indexing). É contraintuitivo mas é padrão universal.'}},
  {content:'<h3>Debug: Encontrando Erros</h3><p><strong>Debugging</strong> é encontrar e corrigir erros no código. Todo programador gasta mais tempo debugando do que escrevendo código novo.</p><p>Tipos de erro: <strong>sintaxe</strong> (escreveu errado — o computador nem roda), <strong>lógica</strong> (roda mas dá resultado errado — mais difícil de achar), <strong>runtime</strong> (roda mas trava no meio).</p><p>Técnicas: <em>print debugging</em> (mostrar valores em cada passo), <em>rubber duck debugging</em> (explicar o código em voz alta — funciona de verdade!), usar um <em>debugger</em> (ferramenta que para o código linha por linha).</p>',quiz:{q:'Qual tipo de erro é mais difícil de encontrar?',o:['Erro de sintaxe','Erro de lógica','Erro de digitação','Erro de compilação'],c:1,exp:'Erros de lógica são os mais difíceis porque o programa roda sem travar, mas produz resultado errado. Erros de sintaxe são fáceis — o computador avisa onde está.'}},
  {content:'<h3>Fluxogramas</h3><p>Um <strong>fluxograma</strong> é a representação visual de um algoritmo. Usa formas geométricas padronizadas:</p><ul><li><strong>Oval</strong> — Início/Fim</li><li><strong>Retângulo</strong> — Processo/Ação</li><li><strong>Losango</strong> — Decisão (Sim/Não)</li><li><strong>Paralelogramo</strong> — Entrada/Saída de dados</li><li><strong>Setas</strong> — Fluxo/Direção</li></ul><p>Antes de escrever código, desenhe o fluxograma. É mais fácil encontrar erros de lógica num desenho do que num código complexo.</p>',quiz:{q:'Qual forma geométrica representa uma DECISÃO no fluxograma?',o:['Retângulo','Oval','Losango','Círculo'],c:2,exp:'O losango (diamante) representa decisões no fluxograma — pontos onde o fluxo se divide em dois caminhos baseado em uma condição (Sim/Não, Verdadeiro/Falso).'}},
  {content:'<h3>Seu Primeiro Pseudocódigo</h3><p><strong>Pseudocódigo</strong> é um meio-termo entre português e código real. Você escreve a lógica sem se preocupar com sintaxe de nenhuma linguagem específica.</p><pre><code>INÍCIO\n  LER nome do aluno\n  LER nota1, nota2, nota3\n  media = (nota1 + nota2 + nota3) / 3\n  SE media >= 7:\n    MOSTRAR nome + " está APROVADO!"\n  SENÃO:\n    MOSTRAR nome + " está em RECUPERAÇÃO"\nFIM</code></pre><p>Exercício: escreva o pseudocódigo de um caixa eletrônico (verificar senha, mostrar saldo, sacar dinheiro). Pense nos passos antes de programar!</p>',quiz:{q:'Para que serve pseudocódigo?',o:['Para rodar programas','Para planejar a lógica antes de programar em uma linguagem real','Para desenhar interfaces','Para testar hardware'],c:1,exp:'Pseudocódigo permite planejar a lógica do programa em linguagem natural antes de traduzir para uma linguagem de programação. Ajuda a focar no "o quê" antes do "como".'}}
]);
updateIndex(52, [{quiz:{q:'O que é programação?',o:['Usar computador','Dar instruções precisas para computadores','Consertar hardware','Navegar na internet'],c:1,exp:'Programação é escrever instruções que computadores executam.'}},{quiz:{q:'O que é um algoritmo?',o:['Tipo de computador','Sequência de passos para resolver um problema','Linguagem de programação','Aplicativo'],c:1,exp:'Algoritmo é sequência de passos para resolver um problema.'}},{quiz:{q:'O que é variável?',o:['Tipo de erro','Espaço que armazena valor com nome','Comando de repetição','Função matemática'],c:1,exp:'Variável é espaço na memória com nome que armazena valor.'}},{quiz:{q:'O que faz uma condicional?',o:['Repete código','Permite tomar decisões','Cria variáveis','Desenha na tela'],c:1,exp:'Condicionais permitem ao programa escolher caminhos diferentes.'}},{quiz:{q:'Quando usar ENQUANTO?',o:['Nunca','Quando não sabe quantas vezes repetir','Exatamente 10 vezes','Para parar'],c:1,exp:'ENQUANTO repete até condição se tornar falsa.'}},{quiz:{q:'Vantagem de funções?',o:['Programa mais rápido','Reutilizar código','Menos memória','É obrigatório'],c:1,exp:'Funções permitem reutilizar código sem repetir.'}},{quiz:{q:'Índice do primeiro elemento?',o:['1','0','-1','Depende'],c:1,exp:'Primeiro elemento tem índice 0.'}},{quiz:{q:'Erro mais difícil?',o:['Sintaxe','Lógica','Digitação','Compilação'],c:1,exp:'Erros de lógica — programa roda mas dá resultado errado.'}},{quiz:{q:'Decisão no fluxograma?',o:['Retângulo','Oval','Losango','Círculo'],c:2,exp:'Losango representa decisões.'}},{quiz:{q:'Para que serve pseudocódigo?',o:['Rodar programas','Planejar lógica antes de programar','Desenhar interfaces','Testar hardware'],c:1,exp:'Pseudocódigo planeja lógica antes da linguagem real.'}}]);

console.log('\nDone! Enriched modules 46 and 52 with full educational content.');
console.log('Remaining modules have structural content — can be enriched in future sessions.');
