/**
 * Generate new modules for Escola Liberal
 * Run: node scripts/generate-modules.js
 * Creates: lessons/mod-38.json through mod-60.json + updates index.json
 */
const fs = require('fs');
const path = require('path');

const LESSONS_DIR = path.join(__dirname, '..', 'lessons');
const INDEX_PATH = path.join(LESSONS_DIR, 'index.json');

// Load existing index
const index = JSON.parse(fs.readFileSync(INDEX_PATH, 'utf8'));
const startIdx = index.length; // 38

// Helper to create a lesson
function L(title, sub, xp, content, q, o, c, exp) {
  return { title, sub, xp, content, quiz: { q, o, c, exp } };
}

// =====================================================
// EXPANSION MODULES (14 modules, indices 38-51)
// =====================================================
const expansionModules = [
  // GEOGRAFIA +2
  {
    title: 'Economia dos Países', desc: 'PIB, desenvolvimento, tigres asiáticos e o papel do comércio internacional',
    icon: '🌎', color: 'mint', discipline: 'geografia',
    lessons: [
      L('O que é PIB?','Medindo a riqueza das nações',25,
        '<h3>PIB — O Termômetro da Economia</h3><p>O <strong>Produto Interno Bruto (PIB)</strong> é a soma de todos os bens e serviços produzidos em um país durante um ano. É como medir a "receita total" de uma nação.</p><p>O Brasil tem o 9º maior PIB do mundo (~R$ 10 trilhões), mas quando dividimos pela população (PIB per capita), caímos para a 80ª posição. Isso mostra que tamanho não é tudo — <em>distribuição importa</em>.</p><p>Países como Luxemburgo e Suíça têm PIBs totais pequenos, mas PIB per capita altíssimo. Já a Índia tem PIB gigante mas per capita baixo.</p>',
        'O que o PIB per capita mede?',['A população total do país','A riqueza produzida dividida pelo número de habitantes','O valor da moeda','A dívida do governo'],1,
        'PIB per capita = PIB total ÷ população. Mostra a produção média por pessoa, indicando o nível de desenvolvimento econômico.'),
      L('Países Desenvolvidos vs Em Desenvolvimento','O que separa ricos e pobres',25,
        '<h3>O Abismo entre Nações</h3><p>Países desenvolvidos (EUA, Japão, Alemanha) têm: alta renda per capita, infraestrutura avançada, educação de qualidade e instituições fortes.</p><p>Países em desenvolvimento (Brasil, Índia, Nigéria) lutam com: desigualdade, corrupção, infraestrutura precária e dependência de commodities.</p><p>A diferença-chave? <strong>Instituições</strong>. Países com regras claras, propriedade privada protegida e liberdade econômica tendem a prosperar. Não é sobre recursos naturais — o Japão quase não tem, mas é rico. Venezuela tem petróleo, mas é pobre.</p>',
        'O que mais diferencia países ricos de pobres?',['Quantidade de recursos naturais','Tamanho do território','Qualidade das instituições e regras','Número de habitantes'],2,
        'Instituições fortes (direito de propriedade, contratos, baixa corrupção) são o fator mais determinante para o desenvolvimento, segundo economistas como Douglass North e Daron Acemoglu.'),
      L('Os Tigres Asiáticos','Como 4 países pobres ficaram ricos em 30 anos',30,
        '<h3>O Milagre Asiático</h3><p>Coreia do Sul, Taiwan, Singapura e Hong Kong eram extremamente pobres nos anos 1960. Em apenas 30 anos, tornaram-se potências econômicas. Como?</p><ul><li><strong>Educação massiva</strong> — investiram pesado em capital humano</li><li><strong>Abertura comercial</strong> — exportaram para o mundo</li><li><strong>Poupança alta</strong> — investiram em vez de consumir</li><li><strong>Estado enxuto</strong> — regulação mínima, mercado livre</li></ul><p>A Coreia do Sul em 1960 tinha PIB per capita menor que o de Gana. Hoje é 15x maior. A lição? <em>Políticas certas importam mais que recursos.</em></p>',
        'Qual NÃO foi uma estratégia dos Tigres Asiáticos?',['Investimento massivo em educação','Protecionismo total e mercado fechado','Abertura comercial e exportações','Alta taxa de poupança'],1,
        'Os Tigres Asiáticos foram abertos ao comércio internacional, não protecionistas. Exportar foi fundamental para seu crescimento acelerado.'),
      L('Comércio Internacional','Por que países comerciam entre si',25,
        '<h3>Vantagem Comparativa</h3><p>David Ricardo explicou em 1817: mesmo que um país seja melhor em <em>tudo</em>, ainda vale a pena comerciar. Cada país deve produzir aquilo em que é <strong>relativamente</strong> mais eficiente.</p><p>O Brasil exporta soja e minério porque temos terra fértil e minerais abundantes. Importamos chips e software porque outros países são mais eficientes nisso.</p><p>Comércio livre gera: preços menores, mais variedade, inovação e especialização. Barreiras comerciais (tarifas, cotas) protegem poucos produtores locais mas prejudicam milhões de consumidores.</p>',
        'O que é vantagem comparativa?',['Ser o melhor do mundo em tudo','Produzir aquilo em que você é relativamente mais eficiente','Ter mais recursos naturais','Ter a moeda mais forte'],1,
        'Vantagem comparativa (Ricardo, 1817): cada país deve focar no que produz com menor custo de oportunidade, mesmo que outro país seja "melhor" em tudo.'),
      L('Globalização','O mundo conectado',20,
        '<h3>Um Mundo Sem Fronteiras Econômicas</h3><p>Globalização é a integração econômica entre países via comércio, investimentos e tecnologia. Seu celular tem peças de 20+ países. Sua roupa foi costurada em Bangladesh. Seu café veio da Colômbia.</p><p>Benefícios: produtos mais baratos, acesso a tecnologia, crescimento econômico. Críticas: desigualdade entre países, perda de empregos locais, dependência.</p><p>O Brasil é um dos países <em>mais fechados</em> do G20 em termos de comércio. Isso encarece tudo — de carros a eletrônicos.</p>',
        'Qual é um efeito da globalização?',['Produtos mais caros','Menos variedade de produtos','Maior integração econômica entre países','Isolamento tecnológico'],2,
        'Globalização conecta economias, resultando em maior integração, produtos mais baratos por competição, e acesso a tecnologias desenvolvidas em outros países.'),
      L('Blocos Econômicos','Mercosul, UE, NAFTA',20,
        '<h3>Quando Países se Juntam</h3><p>Blocos econômicos são acordos entre países para facilitar o comércio entre si. Os principais:</p><ul><li><strong>União Europeia (UE)</strong> — 27 países, moeda única (euro), livre circulação</li><li><strong>Mercosul</strong> — Brasil, Argentina, Uruguai, Paraguai — tarifa externa comum</li><li><strong>USMCA</strong> (ex-NAFTA) — EUA, Canadá, México</li></ul><p>A UE é o bloco mais integrado do mundo — além de livre comércio, tem parlamento, tribunal e moeda comuns. O Mercosul é mais limitado e frequentemente criticado por não cumprir suas próprias regras.</p>',
        'Qual é o bloco econômico mais integrado do mundo?',['Mercosul','USMCA','União Europeia','BRICS'],2,
        'A União Europeia vai além do livre comércio: tem moeda única (euro), parlamento, tribunal, livre circulação de pessoas e mercado único com regras harmonizadas.'),
      L('China: Gigante Econômico','Como a China se tornou potência',25,
        '<h3>De Mao a Mercado</h3><p>Em 1978, a China era um dos países mais pobres do mundo. Deng Xiaoping iniciou reformas: <strong>zonas econômicas especiais</strong>, abertura a investimento estrangeiro e incentivo à produção.</p><p>O resultado: 800 milhões de pessoas saíram da pobreza. O PIB cresceu 10% ao ano por 3 décadas. Hoje a China é a 2ª maior economia do mundo.</p><p>Mas o modelo tem problemas: autoritarismo, dívida gigante, manipulação cambial e trabalho em condições precárias. A lição: <em>liberdade econômica funciona</em>, mas sem liberdade política os ganhos são frágeis.</p>',
        'O que impulsionou o crescimento econômico da China a partir de 1978?',['Comunismo puro','Reformas de mercado e abertura econômica','Descoberta de petróleo','Ajuda financeira dos EUA'],1,
        'As reformas de Deng Xiaoping (1978) abriram a China ao mercado: zonas especiais, investimento estrangeiro, propriedade privada parcial. Foi liberdade econômica, não comunismo, que gerou o crescimento.'),
      L('Índia: Economia Emergente','Bilhões de pessoas, trilhões de oportunidades',20,
        '<h3>O Gigante Despertando</h3><p>A Índia tem 1.4 bilhão de habitantes e é a 5ª maior economia do mundo. Até 1991, era uma economia fechada e burocrática. As reformas liberalizantes de Manmohan Singh mudaram tudo.</p><p>Hoje a Índia lidera em: tecnologia (Bangalore é o "Silicon Valley indiano"), farmácia (produz 60% das vacinas do mundo) e serviços de TI.</p><p>Desafios: pobreza extrema, infraestrutura precária, burocracia e desigualdade entre castas. Mas com a população mais jovem do mundo, o potencial é imenso.</p>',
        'Em que setor a Índia se destaca globalmente?',['Petróleo','Agricultura de subsistência','Tecnologia e serviços de TI','Indústria automobilística'],2,
        'A Índia é líder mundial em serviços de TI e tecnologia. Bangalore é chamada de "Silicon Valley da Índia", e empresas como Infosys, Wipro e TCS são gigantes globais.'),
      L('África: O Continente do Futuro','Desafios e oportunidades do continente mais jovem',25,
        '<h3>Além dos Estereótipos</h3><p>A África não é um país — são 54 nações diversas. Algumas crescem rápido (Ruanda, Etiópia, Gana), outras enfrentam conflitos e pobreza.</p><p>O continente tem: 60% das terras aráveis não cultivadas do mundo, a população mais jovem (idade mediana: 19 anos) e recursos minerais abundantes.</p><p>Desafios reais: governança fraca, corrupção, infraestrutura insuficiente e legado colonial. Mas a tecnologia está pulando etapas — o M-Pesa (pagamento por celular) nasceu no Quênia antes de existir no Brasil.</p>',
        'Qual é uma vantagem demográfica da África?',['Ter a população mais velha do mundo','Ter pouca diversidade cultural','Ter a população mais jovem do mundo','Ter poucos recursos naturais'],2,
        'A África tem a população mais jovem do mundo (idade mediana ~19 anos). Isso significa força de trabalho crescente e potencial de consumo futuro — o chamado "dividendo demográfico".'),
      L('O Futuro da Economia Global','Tendências e previsões',25,
        '<h3>Para Onde o Mundo Vai?</h3><p>Tendências que vão moldar a economia nas próximas décadas:</p><ul><li><strong>IA e automação</strong> — mudarão 40% dos empregos</li><li><strong>Energia limpa</strong> — transição de petróleo para solar/eólica</li><li><strong>Envelhecimento</strong> — Europa e Japão terão menos trabalhadores</li><li><strong>Moedas digitais</strong> — CBDCs e cripto desafiando bancos centrais</li></ul><p>O mundo em 2050 será muito diferente. Os países que investirem em educação, tecnologia e instituições fortes vão liderar. Os que dependerem de commodities e protecionismo ficarão para trás.</p>',
        'Qual tendência NÃO deve impactar a economia global nas próximas décadas?',['Inteligência artificial','Envelhecimento populacional','Volta ao padrão-ouro','Transição energética'],2,
        'O retorno ao padrão-ouro é extremamente improvável. IA, envelhecimento e transição energética são tendências confirmadas que já estão em curso.')
    ]
  },
  {
    title: 'Recursos Naturais e Comércio', desc: 'Petróleo, água, minerais — como recursos moldam nações e conflitos',
    icon: '⛏️', color: 'sage', discipline: 'geografia',
    lessons: [
      L('Petróleo: O Ouro Negro','Como o petróleo moldou o século XX',25,'<h3>O Recurso que Mudou Tudo</h3><p>O petróleo é a principal fonte de energia do mundo, responsável por 31% da matriz energética global. Países produtores (Arábia Saudita, Rússia, EUA) têm enorme poder geopolítico.</p><p>A OPEP (Organização dos Países Exportadores de Petróleo) controla ~40% da produção mundial e pode manipular preços reduzindo ou aumentando a oferta.</p><p>O Brasil descobriu o pré-sal em 2006 — uma das maiores reservas do século XXI. Isso nos tornou um dos 10 maiores produtores mundiais.</p>','O que é a OPEP?',['Uma empresa de petróleo','Um cartel de países produtores de petróleo','Uma ONG ambiental','Um banco internacional'],1,'A OPEP é um cartel de 13 países exportadores de petróleo que coordenam produção para influenciar preços globais. Arábia Saudita é o membro mais influente.'),
      L('Água: O Recurso do Futuro','Escassez hídrica e conflitos',25,'<h3>Água Doce em Risco</h3><p>Apenas 2.5% da água da Terra é doce, e só 1% está acessível. Até 2025, 1.8 bilhão de pessoas viverão em regiões com escassez absoluta de água.</p><p>O Brasil tem 12% da água doce do mundo — mas distribuída de forma desigual. O Nordeste sofre secas enquanto a Amazônia tem excesso.</p><p>Conflitos por água já existem: Turquia vs Síria/Iraque (rios Tigre e Eufrates), Índia vs Paquistão (rio Indo), Egito vs Etiópia (Nilo). Água é o petróleo do século XXI.</p>','Qual % da água da Terra é doce acessível?',['50%','12%','~1%','25%'],2,'Apenas ~1% da água do planeta é doce e acessível. O restante está em geleiras (1.5%) ou é água salgada (97.5%).'),
      L('Minerais Estratégicos','Lítio, cobalto e terras raras',25,'<h3>Os Minerais da Era Digital</h3><p>Seu celular contém ~30 minerais diferentes. Os mais estratégicos hoje são:</p><ul><li><strong>Lítio</strong> — baterias de celular e carros elétricos (Chile, Austrália, Argentina)</li><li><strong>Cobalto</strong> — baterias (60% vem do Congo, muitas vezes com trabalho infantil)</li><li><strong>Terras raras</strong> — chips, ímãs, motores elétricos (China controla 60%)</li></ul><p>Quem controla esses minerais terá poder no século XXI, assim como quem controlou petróleo no XX.</p>','Qual país controla a maior parte das terras raras?',['EUA','Brasil','China','Austrália'],2,'A China produz ~60% das terras raras do mundo e refina 85%. Isso dá enorme poder geopolítico em um mundo cada vez mais dependente de eletrônicos.'),
      L('Agronegócio Brasileiro','O celeiro do mundo',20,'<h3>Brasil: Potência Agrícola</h3><p>O Brasil é o maior exportador mundial de soja, café, carne bovina, suco de laranja e açúcar. O agronegócio representa ~25% do PIB.</p><p>Usamos apenas 7.6% do território para agricultura — temos potencial de crescer sem desmatar. Tecnologia (Embrapa) multiplicou a produtividade por 4 em 40 anos.</p><p>Paradoxo: alimentamos 800 milhões de pessoas no mundo, mas 33 milhões de brasileiros passam fome. O problema não é produção — é distribuição e pobreza.</p>','Qual é a posição do Brasil nas exportações de soja?',['3º lugar','2º lugar','1º lugar mundial','5º lugar'],2,'O Brasil é o maior exportador de soja do mundo, superando os EUA em 2020. O agronegócio brasileiro alimenta cerca de 800 milhões de pessoas globalmente.'),
      L('Desmatamento e Economia','O custo econômico da destruição ambiental',25,'<h3>Quanto Vale uma Floresta em Pé?</h3><p>Serviços ecossistêmicos (polinização, chuvas, purificação de água) da Amazônia valem estimados US$ 8.2 trilhões por ano. Desmatar para criar pasto gera uma fração disso.</p><p>A "tragédia dos comuns": quando ninguém é dono, ninguém cuida. Definir propriedade privada sobre florestas pode ser mais eficaz que regulação estatal.</p><p>Países que mais desmatam tendem a ter direitos de propriedade fracos. Quando o proprietário lucra com a floresta em pé (créditos de carbono, ecoturismo), ele a protege.</p>','O que é a "tragédia dos comuns"?',['Uma peça de teatro sobre economia','Quando recursos sem dono são superexplorados','Quando o governo privatiza tudo','Quando há inflação alta'],1,'A tragédia dos comuns (Garrett Hardin, 1968): recursos sem proprietário claro são superexplorados porque ninguém tem incentivo individual para preservá-los.'),
      L('Energia Solar e Eólica','A revolução renovável',20,'<h3>O Futuro é Renovável</h3><p>O custo da energia solar caiu 89% desde 2010. A eólica caiu 70%. Em muitos países, renováveis já são mais baratas que carvão e gás natural.</p><p>O Brasil tem vantagem: 83% da nossa eletricidade já é renovável (hidrelétricas + eólica + solar). Temos sol abundante no Nordeste e vento constante no litoral.</p><p>Desafios: intermitência (sol não brilha à noite), armazenamento (baterias ainda caras) e minerais para painéis e turbinas. Mas a tendência é irreversível.</p>','Quanto caiu o custo da energia solar desde 2010?',['10%','30%','~89%','50%'],2,'O custo da energia solar fotovoltaica caiu ~89% entre 2010 e 2023, tornando-a a fonte de energia mais barata em muitas regiões do mundo.'),
      L('Mudanças Climáticas','O debate econômico',25,'<h3>Economia do Clima</h3><p>O aquecimento global é uma <strong>externalidade negativa</strong>: quem polui não paga o custo total. Soluções econômicas incluem:</p><ul><li><strong>Taxa de carbono</strong> — cobrar pelo CO₂ emitido</li><li><strong>Mercado de carbono</strong> — créditos negociáveis</li><li><strong>Inovação</strong> — tecnologia mais limpa</li></ul><p>O debate: regulação pesada pode frear o crescimento. Mas não fazer nada pode custar 5-20% do PIB global até 2100 (Stern Review).</p>','O que é uma externalidade negativa?',['Um imposto sobre empresas','Quando o custo de uma ação recai sobre terceiros','Uma queda no PIB','Uma crise financeira'],1,'Externalidade negativa: quando alguém causa custos a terceiros sem compensá-los. Poluição é o exemplo clássico — a fábrica lucra, mas a sociedade paga com saúde e clima.'),
      L('O Mapa da Fome','Insegurança alimentar no mundo',25,'<h3>Por Que Pessoas Passam Fome?</h3><p>O mundo produz comida suficiente para 10 bilhões de pessoas, mas 735 milhões passam fome. O problema não é produção — é:</p><ul><li><strong>Pobreza</strong> — pessoas não podem comprar comida</li><li><strong>Conflitos</strong> — guerras destroem agricultura e logística</li><li><strong>Desperdício</strong> — 1/3 da comida produzida é desperdiçada</li><li><strong>Logística</strong> — comida não chega onde precisa</li></ul><p>Solução? Mais comércio livre, menos barreiras, mais tecnologia agrícola e direitos de propriedade para pequenos agricultores.</p>','Qual a principal causa da fome no mundo?',['Falta de produção global','Superpopulação','Pobreza e falta de acesso','Falta de terras aráveis'],2,'A fome é causada principalmente por pobreza (pessoas não podem comprar comida) e não por falta de produção global. Guerras, logística e desperdício agravam o problema.'),
      L('Mineração no Brasil','Riqueza e responsabilidade',20,'<h3>O Subsolo Brasileiro</h3><p>O Brasil é rico em minério de ferro (2º maior produtor), nióbio (85% da produção mundial), bauxita, ouro e manganês. A mineração gera 4% do PIB e centenas de milhares de empregos.</p><p>Mas tragédias como Mariana (2015) e Brumadinho (2019) mostram os riscos. Barragens de rejeitos, contaminação de rios e destruição de comunidades.</p><p>O dilema: mineração é essencial para a economia e para a transição energética (precisamos de minerais para baterias e painéis solares). Mas precisa ser feita com responsabilidade ambiental.</p>','Em qual mineral o Brasil é líder mundial de produção?',['Ouro','Lítio','Nióbio','Diamante'],2,'O Brasil produz ~85% do nióbio mundial. O nióbio é usado em aço de alta resistência (construção, aeronáutica) e supercondutores.'),
      L('Geopolítica dos Recursos','Quem controla os recursos controla o mundo',30,'<h3>Poder e Recursos</h3><p>A história do mundo é, em grande parte, a história do controle de recursos. Guerras do Golfo: petróleo. Colonização da África: ouro, diamantes, borracha. Guerra na Ucrânia: gás natural e trigo.</p><p>Hoje, a disputa é por: <strong>lítio</strong> (América do Sul), <strong>terras raras</strong> (China), <strong>chips</strong> (Taiwan), <strong>água</strong> (Oriente Médio).</p><p>A lição para o Brasil: temos recursos abundantes, mas sem <em>instituições fortes e tecnologia</em>, seremos sempre exportadores de matéria-prima barata e importadores de produtos caros. Agregar valor é o caminho.</p>','O que o Brasil precisa para não ser apenas exportador de matéria-prima?',['Mais terras aráveis','Mais petróleo','Agregar valor com tecnologia e instituições fortes','Mais impostos sobre exportação'],2,'Exportar matéria-prima bruta gera pouco valor. Países que agregam tecnologia (transformar minério em aço especial, soja em alimento processado) capturam muito mais riqueza.')
    ]
  }
];

// For brevity, I'll generate the remaining 12 expansion modules + 9 new discipline modules
// with a template approach

function generateModule(title, desc, icon, color, discipline, topics) {
  return {
    title, desc, icon, color, discipline,
    lessons: topics.map((t, i) => ({
      title: t.title,
      sub: t.sub,
      xp: t.xp || 25,
      content: t.content,
      quiz: { q: t.q, o: t.o, c: t.c, exp: t.exp }
    }))
  };
}

// American History expansion (ENGLISH)
const amHistory1 = generateModule('Founding Fathers & Constitution',
  'Washington, Jefferson, Madison and the ideas that shaped America',
  '🗽', 'sky', 'history',
  [
    {title:'The Road to Independence',sub:'Why colonies rebelled',xp:25,content:'<h3>Taxation Without Representation</h3><p>By 1770, American colonists were frustrated. Britain taxed them on tea, stamps, and paper — but gave them <strong>no voice in Parliament</strong>. The famous cry "No taxation without representation!" captured the core issue.</p><p>Key events: the Boston Massacre (1770), the Boston Tea Party (1773), and the Intolerable Acts (1774) pushed colonists from protest to revolution.</p><p>The ideas behind the revolution came from <em>John Locke</em>: natural rights to life, liberty, and property. Government exists to protect these rights — and if it fails, people can change it.</p>',q:'What was the main complaint of American colonists?',o:['High prices for tea','Being taxed without representation in Parliament','Not having enough land','Religious persecution'],c:1,exp:'The colonists\' core complaint was being taxed by a government in which they had no representatives. This principle — no taxation without representation — became a founding idea of American democracy.'},
    {title:'The Declaration of Independence',sub:'Life, liberty, and the pursuit of happiness',xp:25,content:'<h3>July 4, 1776</h3><p>Thomas Jefferson, at just 33 years old, drafted the Declaration of Independence. Its most famous words: <em>"We hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights."</em></p><p>The document did three things: declared independence from Britain, listed grievances against King George III, and established a philosophy of government based on <strong>natural rights</strong>.</p><p>It was revolutionary — not just politically, but intellectually. For the first time, a nation was founded on an <em>idea</em> rather than ethnicity, religion, or conquest.</p>',q:'Who wrote the Declaration of Independence?',o:['George Washington','Benjamin Franklin','Thomas Jefferson','John Adams'],c:2,exp:'Thomas Jefferson wrote the Declaration of Independence in 1776 at age 33. He drew heavily on the philosophy of John Locke and the ideals of the Enlightenment.'},
    {title:'George Washington',sub:'The man who could have been king',xp:25,content:'<h3>The Indispensable Man</h3><p>George Washington led the Continental Army to victory against Britain, then did something extraordinary: <strong>he gave up power</strong>. After two terms as president, he voluntarily stepped down.</p><p>King George III of England said: "If he does that, he will be the greatest man in the world." In an era of kings and emperors, peacefully leaving power was revolutionary.</p><p>Washington set precedents that defined American democracy: the two-term limit, civilian control of the military, and the peaceful transfer of power.</p>',q:'Why was Washington\'s decision to step down so remarkable?',o:['He was too old to continue','In an era of kings, voluntarily giving up power was unprecedented','He lost the election','He was forced out by Congress'],c:1,exp:'Washington voluntarily giving up power after two terms was unprecedented. Most leaders in history clung to power. His example established the democratic tradition of peaceful power transfer.'},
    {title:'The Constitution',sub:'The framework of freedom',xp:30,content:'<h3>A Government of Laws, Not Men</h3><p>The U.S. Constitution (1787) created a system designed to <strong>limit government power</strong>. Its key innovations:</p><ul><li><strong>Separation of Powers</strong> — Legislative, Executive, Judicial</li><li><strong>Checks and Balances</strong> — each branch limits the others</li><li><strong>Federalism</strong> — power divided between states and federal government</li><li><strong>Bill of Rights</strong> — 10 amendments protecting individual freedoms</li></ul><p>James Madison, the "Father of the Constitution," believed that <em>"If men were angels, no government would be necessary."</em> The Constitution assumes people are imperfect — and builds safeguards accordingly.</p>',q:'What is the main purpose of "checks and balances"?',o:['To make government efficient','To prevent any one branch from having too much power','To check government spending','To balance the budget'],c:1,exp:'Checks and balances ensure no single branch (executive, legislative, judicial) becomes too powerful. Each can limit the others — e.g., the president can veto laws, but Congress can override vetoes.'},
    {title:'The Bill of Rights',sub:'Your fundamental freedoms',xp:25,content:'<h3>The First 10 Amendments</h3><p>Many states refused to ratify the Constitution without explicit protections for individual rights. The result: the Bill of Rights (1791).</p><p>Key amendments: <strong>1st</strong> — freedom of speech, religion, press. <strong>2nd</strong> — right to bear arms. <strong>4th</strong> — protection from unreasonable searches. <strong>5th</strong> — right against self-incrimination. <strong>10th</strong> — powers not given to federal government belong to states.</p><p>These rights limit what the government can do <em>to you</em>. They don\'t grant privileges — they recognize pre-existing natural rights.</p>',q:'What does the 1st Amendment protect?',o:['The right to bear arms','Freedom of speech, religion, and press','The right to vote','Protection from searches'],c:1,exp:'The 1st Amendment protects five freedoms: speech, religion, press, assembly, and petition. It\'s considered the most fundamental because it enables all other political participation.'},
    {title:'Thomas Jefferson',sub:'Philosopher of freedom',xp:20,content:'<h3>The Sage of Monticello</h3><p>Jefferson was a contradiction: he wrote "all men are created equal" while owning over 600 enslaved people. Yet his ideas shaped the modern world.</p><p>He believed in: limited government, individual liberty, public education, religious freedom, and agrarian democracy. He doubled America\'s size with the Louisiana Purchase (1803).</p><p>His famous quote: <em>"The government that governs least, governs best."</em> This idea — that freedom means limiting state power — remains central to American political thought.</p>',q:'What philosophical tradition did Jefferson represent?',o:['Strong central government','Limited government and individual liberty','Military expansion','Religious theocracy'],c:1,exp:'Jefferson championed limited government, individual rights, and personal liberty. His philosophy shaped American libertarian and classical liberal traditions.'},
    {title:'Benjamin Franklin',sub:'Inventor, diplomat, founding father',xp:20,content:'<h3>The First American</h3><p>Franklin was a printer, scientist, inventor, diplomat, and founding father. He proved lightning was electricity, invented bifocals, and helped draft the Declaration of Independence.</p><p>His economic views were remarkably modern: he advocated for <strong>free trade, sound money, and thrift</strong>. His "Poor Richard\'s Almanack" spread financial wisdom: "A penny saved is a penny earned."</p><p>At 81, he was the oldest delegate at the Constitutional Convention. His wisdom and humor helped bridge disagreements between rival factions.</p>',q:'What was Franklin\'s economic philosophy?',o:['Government spending','Free trade, thrift, and sound money','High tariffs','Printing more money'],c:1,exp:'Franklin advocated free trade, fiscal responsibility, and personal thrift. His advice on saving, investing, and avoiding debt in "Poor Richard\'s Almanack" became foundational American financial wisdom.'},
    {title:'Alexander Hamilton',sub:'The man who built American finance',xp:25,content:'<h3>The Financial Architect</h3><p>Hamilton was the first Secretary of the Treasury and arguably the architect of American capitalism. He created:</p><ul><li>The National Bank (predecessor of the Federal Reserve)</li><li>The U.S. Mint and dollar system</li><li>Federal assumption of state debts (built national credit)</li><li>Tariffs to fund the government</li></ul><p>His rival Jefferson wanted an agrarian republic. Hamilton wanted an industrial powerhouse. History proved Hamilton right — manufacturing made America a superpower.</p>',q:'What did Hamilton create as Secretary of Treasury?',o:['The Declaration of Independence','The National Bank and federal financial system','The Bill of Rights','The Supreme Court'],c:1,exp:'Hamilton created the National Bank, U.S. Mint, and federal debt system. He essentially built America\'s financial infrastructure from scratch, establishing the credit and institutions that powered economic growth.'},
    {title:'The Federalist Papers',sub:'Defending the Constitution',xp:25,content:'<h3>85 Essays that Shaped a Nation</h3><p>The Federalist Papers (1787-88) were 85 essays by Hamilton, Madison, and Jay, arguing for ratification of the Constitution.</p><p>Federalist #10 (Madison) is the most famous: it argues that a large republic with many factions is <em>better</em> at protecting liberty than a small democracy, because no single faction can dominate.</p><p>Federalist #51: <em>"Ambition must be made to counteract ambition."</em> The system was designed for imperfect humans — using self-interest to balance power.</p>',q:'What did Federalist #10 argue?',o:['Small governments are better','A large republic with many factions protects liberty','Direct democracy is ideal','The president should have more power'],c:1,exp:'Madison argued in Federalist #10 that a large republic with diverse factions prevents any single group from tyrannizing others. Diversity of interests becomes a safeguard for liberty.'},
    {title:'Legacy of the Founders',sub:'Ideas that changed the world',xp:30,content:'<h3>An Experiment in Freedom</h3><p>The American founding was an experiment: can people govern themselves? Can a nation be built on <em>ideas</em> rather than blood and soil?</p><p>The founders\' key insights:<br>• Power corrupts — divide and limit it<br>• Rights come from nature, not government<br>• Free markets create prosperity<br>• Education is essential for self-governance</p><p>These ideas spread worldwide: the French Revolution, Latin American independence movements, and modern democracies all drew from the American experiment. Imperfect as it was (slavery, exclusion of women), the foundation was sound — and has been expanding ever since.</p>',q:'What was the American founding\'s most revolutionary idea?',o:['A nation built on ideas and self-governance, not blood or conquest','Military supremacy','Economic isolation','Religious uniformity'],c:0,exp:'The most revolutionary aspect was founding a nation on philosophical ideas (natural rights, self-governance, limited government) rather than ethnic identity, religion, or conquest. This was unprecedented in history.'}
  ]
);

const amHistory2 = generateModule('American Economy',
  'From gold rush to Silicon Valley — how America became an economic superpower',
  '💵', 'honey', 'history',
  [
    {title:'The Industrial Revolution in America',sub:'Factories, railroads, and transformation',xp:25,content:'<h3>From Farm to Factory</h3><p>In 1800, 90% of Americans were farmers. By 1900, America was the world\'s largest industrial economy. What happened?</p><p>Key factors: <strong>railroads</strong> connected the continent, <strong>immigration</strong> provided labor, <strong>innovation</strong> (Edison, Bell, Carnegie) created new industries, and <strong>property rights</strong> protected inventors and investors.</p><p>The Transcontinental Railroad (1869) was a game-changer: it connected East Coast markets to West Coast resources, creating the largest free-trade zone in the world.</p>',q:'What percentage of Americans were farmers in 1800?',o:['10%','50%','~90%','30%'],c:2,exp:'About 90% of Americans were farmers in 1800. Industrialization, railroads, and urbanization transformed the economy so dramatically that by 1900, manufacturing output exceeded agriculture.'},
    {title:'Robber Barons or Captains of Industry?',sub:'Carnegie, Rockefeller, and the Gilded Age',xp:25,content:'<h3>Giants of American Capitalism</h3><p>Andrew Carnegie (steel), John D. Rockefeller (oil), and J.P. Morgan (banking) built empires that transformed America. Critics called them "robber barons." Supporters called them "captains of industry."</p><p>Carnegie reduced steel prices by 80%, making bridges, railroads, and skyscrapers affordable. Rockefeller cut kerosene prices by 90%, bringing light to millions. Both later gave away most of their fortunes to charity.</p><p>The debate continues: were they exploitative monopolists or visionary entrepreneurs? Probably both. Their innovations created immense wealth, but their labor practices were often brutal.</p>',q:'What did Carnegie do to steel prices?',o:['Raised them to maximize profit','Reduced them by ~80% through innovation','Kept them stable','Doubled them with tariffs'],c:1,exp:'Carnegie\'s innovations in steel production reduced prices by about 80%. This made construction cheaper and enabled America\'s infrastructure boom — bridges, railroads, skyscrapers.'},
    {title:'The Great Depression',sub:'When everything collapsed',xp:30,content:'<h3>1929: The Crash</h3><p>The stock market crashed on October 29, 1929 ("Black Tuesday"). What followed was the worst economic crisis in modern history: 25% unemployment, bank failures, breadlines.</p><p>Causes: <strong>Federal Reserve</strong> contracted money supply (Milton Friedman\'s analysis), <strong>Smoot-Hawley Tariff</strong> killed international trade, and <strong>bank runs</strong> destroyed savings.</p><p>The lesson: government policy can make crises worse. The Fed\'s tight money policy and protectionist tariffs turned a recession into a catastrophe. Free-market economists argue the Depression lasted so long <em>because</em> of intervention, not despite it.</p>',q:'According to Milton Friedman, what worsened the Great Depression?',o:['Too little government spending','The Federal Reserve contracting the money supply','Too much free trade','Low taxes'],c:1,exp:'Friedman showed that the Federal Reserve dramatically contracted the money supply (by ~1/3) during the Depression, turning a normal recession into a catastrophe. This is now mainstream economic consensus.'},
    {title:'World War II Economy',sub:'The arsenal of democracy',xp:25,content:'<h3>War and Prosperity</h3><p>WWII ended the Depression — not through government spending per se, but through <strong>full mobilization of resources</strong>. Factories that made cars now made tanks. Unemployment went from 25% to nearly 0%.</p><p>America produced: 300,000 aircraft, 86,000 tanks, 2.7 million machine guns, and 6,500 ships in just 4 years. This industrial might won the war.</p><p>After the war, America had 50% of global GDP. Europe and Japan were in ruins. This dominance launched the "American Century" of economic leadership.</p>',q:'What percentage of global GDP did America have after WWII?',o:['10%','25%','~50%','75%'],c:2,exp:'After WWII, America had roughly 50% of global GDP because it was the only major industrial nation not physically destroyed by the war. This economic dominance shaped the global order for decades.'},
    {title:'The Post-War Boom',sub:'Suburbs, highways, and the American Dream',xp:20,content:'<h3>1945-1970: The Golden Age</h3><p>The post-war era was America\'s economic golden age: rising wages, growing middle class, suburban expansion, and the Interstate Highway System.</p><p>Key drivers: GI Bill (education for veterans), Bretton Woods system (stable currencies), and technological innovation (TV, jet travel, computers).</p><p>A single-income family could buy a house, a car, and send kids to college. Real wages grew 2-3% per year. This era shaped the "American Dream" ideal.</p>',q:'What was the GI Bill?',o:['A military tax','Education and housing benefits for veterans','A bill to increase military spending','A healthcare program'],c:1,exp:'The GI Bill (1944) gave returning veterans education funding, low-cost mortgages, and business loans. It created America\'s educated middle class and fueled the post-war economic boom.'},
    {title:'Silicon Valley',sub:'How a valley became the world\'s innovation capital',xp:25,content:'<h3>From Garages to Global Empires</h3><p>Silicon Valley (San Francisco Bay Area) became the world\'s tech capital through a unique combination: Stanford University\'s research, military contracts (Cold War), venture capital, and a culture that celebrated risk-taking and failure.</p><p>Key milestones: HP (1939, in a garage), Intel (1968, the microchip), Apple (1976), Google (1998), Facebook (2004). Each generation built on the last.</p><p>The Valley\'s secret sauce: <strong>people can fail and try again</strong>. Bankruptcy isn\'t shameful — it\'s a learning experience. This tolerance for risk doesn\'t exist in most countries.</p>',q:'What makes Silicon Valley unique?',o:['Government subsidies','A culture that tolerates failure and rewards risk-taking','Low cost of living','Being close to Hollywood'],c:1,exp:'Silicon Valley\'s key ingredient is cultural: failure is not stigmatized but seen as learning. Combined with top universities, venture capital, and immigrant talent, this creates unmatched innovation.'},
    {title:'The Dollar: World Reserve Currency',sub:'Why the world uses American money',xp:25,content:'<h3>The Almighty Dollar</h3><p>The U.S. dollar is the world\'s reserve currency: 60% of global foreign exchange reserves, 88% of international transactions, and oil is priced in dollars ("petrodollar").</p><p>This gives America an "exorbitant privilege" — it can borrow cheaply, print money for imports, and sanction any country by cutting it off from the dollar system.</p><p>The dollar became dominant after Bretton Woods (1944) when it was pegged to gold. Nixon ended the gold standard in 1971, but dollar dominance continued due to trust in U.S. institutions and markets.</p>',q:'What percentage of international transactions use the U.S. dollar?',o:['20%','50%','~88%','100%'],c:2,exp:'About 88% of international transactions use the dollar. This gives America enormous economic power — the ability to borrow cheaply, influence global trade, and use financial sanctions.'},
    {title:'American Entrepreneurship',sub:'The land of startups',xp:20,content:'<h3>Why America Breeds Entrepreneurs</h3><p>America produces more billion-dollar startups ("unicorns") than any other country. Why?</p><ul><li><strong>Easy to start a business</strong> — minimal bureaucracy</li><li><strong>Venture capital</strong> — investors fund risky ideas</li><li><strong>Bankruptcy laws</strong> — you can fail and restart</li><li><strong>Immigration</strong> — 55% of unicorn founders are immigrants</li><li><strong>Culture</strong> — entrepreneurship is admired, not suspicious</li></ul><p>Compare: starting a business in Brazil takes 150 days. In America: 6 days. This difference matters enormously.</p>',q:'What percentage of American unicorn founders are immigrants?',o:['5%','25%','~55%','75%'],c:2,exp:'About 55% of America\'s billion-dollar startups (unicorns) were founded by immigrants. This includes Google (Sergey Brin, Russia), Tesla (Elon Musk, South Africa), and WhatsApp (Jan Koum, Ukraine).'},
    {title:'Inequality in America',sub:'The wealth gap debate',xp:25,content:'<h3>The Land of Opportunity?</h3><p>The top 1% of Americans own more wealth than the bottom 50% combined. CEO pay is 350x the average worker (in 1965 it was 21x).</p><p>Two perspectives:<br><strong>Progressive</strong>: inequality is unjust, needs redistribution.<br><strong>Free-market</strong>: inequality of <em>outcomes</em> is natural; what matters is equality of <em>opportunity</em>.</p><p>The data: social mobility in America has declined. A child born poor today has a 7.5% chance of reaching the top quintile — lower than in Denmark or Canada. The American Dream is harder to achieve than before.</p>',q:'What has happened to social mobility in America?',o:['It has increased dramatically','It has remained the same','It has declined','It was never tracked'],c:2,exp:'Social mobility in America has declined over decades. A child born in the bottom 20% today has lower chances of reaching the top 20% than in several other developed nations.'},
    {title:'The Future of the American Economy',sub:'Challenges and opportunities ahead',xp:25,content:'<h3>What\'s Next?</h3><p>America faces challenges: $34 trillion national debt, aging infrastructure, healthcare costs, and competition from China.</p><p>But strengths remain: world\'s best universities, deepest capital markets, innovation culture, rule of law, and immigration (talent from everywhere).</p><p>Key question: can America maintain the institutions that made it great? Property rights, limited government, free speech, and market competition. <em>Nations decline when they abandon the principles that made them successful.</em></p>',q:'What is America\'s biggest economic strength going forward?',o:['Natural resources','Military power','Innovation culture and institutions','Low labor costs'],c:2,exp:'America\'s greatest economic asset is its innovation ecosystem: top universities, venture capital, tolerance for risk, rule of law, and ability to attract global talent. These institutions drive long-term prosperity.'}
  ]
);

// Remaining expansion modules (simplified generation)
const remainingExpansion = [
  // DIREITO +2
  generateModule('Direito do Consumidor','Seus direitos nas compras, trocas, devoluções e contratos do dia a dia','🛒','sage','direito',[
    {title:'O Código de Defesa do Consumidor',sub:'Seus direitos básicos',xp:25,content:'<h3>CDC: Sua Proteção</h3><p>O Código de Defesa do Consumidor (1990) é uma das leis mais avançadas do mundo. Ele protege você em compras, serviços e contratos.</p><p>Direitos básicos: <strong>informação clara</strong> sobre produtos, <strong>proteção contra publicidade enganosa</strong>, <strong>garantia legal</strong> de 90 dias (duráveis) ou 30 dias (não-duráveis).</p><p>Regra de ouro: o consumidor é a parte mais fraca da relação. A lei presume isso e dá proteções extras.</p>',q:'Qual a garantia legal mínima para produtos duráveis?',o:['7 dias','30 dias','90 dias','1 ano'],c:2,exp:'O CDC garante 90 dias para produtos duráveis (eletrodomésticos, eletrônicos) e 30 dias para não-duráveis (alimentos, produtos de limpeza). Isso é a garantia LEGAL, independente de garantia do fabricante.'},
    {title:'Compras Online',sub:'Direito de arrependimento',xp:25,content:'<h3>7 Dias para Desistir</h3><p>Comprou online e se arrependeu? O artigo 49 do CDC dá <strong>7 dias</strong> para desistir de qualquer compra feita fora do estabelecimento (internet, telefone, catálogo).</p><p>Você não precisa dar motivo. O produto pode estar aberto. O frete de devolução é por conta da empresa. O reembolso deve ser total e imediato.</p><p>Atenção: esse direito <em>não vale</em> para compras em loja física (a não ser que a loja ofereça espontaneamente).</p>',q:'Em compras online, quanto tempo você tem para desistir?',o:['24 horas','3 dias','7 dias','30 dias'],c:2,exp:'O direito de arrependimento (CDC art. 49) dá 7 dias para desistir de compras feitas fora do estabelecimento (internet, telefone). Não precisa justificar e o reembolso deve ser total.'},
    {title:'Propaganda Enganosa',sub:'Quando a publicidade mente',xp:20,content:'<h3>Mentiu? É Crime</h3><p>Publicidade enganosa é proibida pelo CDC. Isso inclui: prometer resultados impossíveis, omitir informações importantes, usar fotos que não representam o produto real.</p><p>Exemplos: hamburger do comercial vs realidade, "sem açúcar" mas com adoçante, "grátis" com asterisco de condições escondidas.</p><p>Se você comprar algo baseado em propaganda enganosa, pode exigir: troca, devolução do dinheiro, ou abatimento do preço.</p>',q:'O que é publicidade enganosa?',o:['Propaganda criativa','Propaganda que mente ou omite informações importantes','Propaganda comparativa','Propaganda em horário nobre'],c:1,exp:'Publicidade enganosa é aquela que mente, exagera ou omite informações que levariam o consumidor a não comprar. É proibida pelo CDC e pode resultar em multa e até processo criminal.'},
    {title:'Produto com Defeito',sub:'Seus direitos quando algo quebra',xp:25,content:'<h3>Quebrou? Você Tem Direitos</h3><p>Se um produto apresentar defeito dentro da garantia (legal + contratual), o fabricante tem <strong>30 dias</strong> para consertar. Se não resolver:</p><ul><li>Troca por produto novo</li><li>Devolução do dinheiro (atualizado)</li><li>Abatimento proporcional do preço</li></ul><p>A escolha é SUA, não da loja. E se o defeito comprometer a segurança (risco à saúde), a troca deve ser imediata, sem esperar 30 dias.</p>',q:'Se o produto não for consertado em 30 dias, quem escolhe a solução?',o:['A loja','O fabricante','O consumidor','O Procon'],c:2,exp:'Se o reparo não é feito em 30 dias, o CONSUMIDOR escolhe entre: troca, devolução do dinheiro, ou abatimento do preço. A lei dá esse poder ao consumidor, não à empresa.'},
    {title:'Serviços: Seus Direitos',sub:'Bancos, telecoms, planos de saúde',xp:25,content:'<h3>Serviços Também Têm Regras</h3><p>O CDC protege consumidores de serviços tanto quanto de produtos. Banco não pode cobrar tarifa sem informar. Telecom não pode mudar contrato unilateralmente. Plano de saúde não pode negar cobertura prevista.</p><p>Cobranças indevidas devem ser devolvidas em <strong>dobro</strong> (art. 42). Se o banco cobrou R$ 50 errado, deve devolver R$ 100.</p><p>Dica prática: sempre guarde comprovantes, contratos e protocolos de atendimento. Em caso de disputa, a prova é sua melhor amiga.</p>',q:'Se um banco cobra tarifa indevida, como deve devolver?',o:['O valor exato','O valor com juros','O dobro do valor cobrado','Depende do banco'],c:2,exp:'O CDC (art. 42) determina que cobranças indevidas sejam devolvidas em DOBRO, mais correção monetária e juros. Isso serve como punição e desincentivo a cobranças abusivas.'},
    {title:'Procon e Pequenas Causas',sub:'Onde reclamar quando seus direitos são violados',xp:20,content:'<h3>Não Se Cale</h3><p>Se seus direitos foram violados, você tem opções:</p><ul><li><strong>SAC da empresa</strong> — primeiro passo, anote o protocolo</li><li><strong>consumidor.gov.br</strong> — plataforma federal, 80% de resolução</li><li><strong>Procon</strong> — órgão de defesa do consumidor (cada estado tem um)</li><li><strong>Juizado Especial</strong> — causas até 20 salários mínimos, sem advogado</li></ul><p>No Juizado Especial (Pequenas Causas), você entra sozinho, sem pagar nada, e a audiência sai em 30-60 dias. Funciona muito bem para problemas de consumo.</p>',q:'Até qual valor é possível ir ao Juizado Especial sem advogado?',o:['5 salários mínimos','10 salários mínimos','20 salários mínimos','40 salários mínimos'],c:2,exp:'No Juizado Especial Cível, causas de até 20 salários mínimos não precisam de advogado. O processo é simples, gratuito e rápido — ideal para conflitos de consumo.'},
    {title:'Contratos Abusivos',sub:'Cláusulas que você pode ignorar',xp:25,content:'<h3>Nem Tudo que Está Escrito Vale</h3><p>Uma cláusula contratual que prejudica excessivamente o consumidor é <strong>nula</strong>, mesmo que você tenha assinado. Exemplos:</p><ul><li>"Não nos responsabilizamos por defeitos" — nula</li><li>"Multa de 100% em caso de cancelamento" — abusiva</li><li>"Podemos alterar o contrato a qualquer momento" — nula</li></ul><p>O CDC protege você de cláusulas que criam <em>desequilíbrio excessivo</em> entre as partes. Se parecer injusto demais, provavelmente é ilegal.</p>',q:'Uma cláusula que diz "não nos responsabilizamos por defeitos" é:',o:['Válida se você assinou','Nula por violar o CDC','Válida em lojas online','Depende do valor da compra'],c:1,exp:'Cláusulas que excluem a responsabilidade do fornecedor por defeitos são NULAS pelo CDC, independente de ter sido assinada. O fornecedor não pode abrir mão da responsabilidade legal.'},
    {title:'Garantia Legal vs Contratual',sub:'Entendendo prazos e cobertura',xp:20,content:'<h3>Duas Garantias, Uma Proteção</h3><p><strong>Garantia legal</strong>: automática, prevista no CDC (30 ou 90 dias). Começa na entrega. Não pode ser retirada.</p><p><strong>Garantia contratual</strong>: oferecida pelo fabricante (ex: 1 ano). Soma-se à legal. É um plus, não uma substituição.</p><p>Garantia estendida (vendida em lojas): é um seguro, não uma garantia. Tem regras próprias e geralmente não vale a pena — a margem da loja é altíssima.</p>',q:'A garantia legal pode ser retirada pelo vendedor?',o:['Sim, se informar na nota fiscal','Sim, em promoções','Não, é irrenunciável','Sim, para produtos usados'],c:2,exp:'A garantia legal é irrenunciável — nenhuma loja pode retirá-la, mesmo em promoções ou "saldão". É um direito do consumidor que não pode ser negociado.'},
    {title:'Recall: Quando o Fabricante Erra',sub:'Chamadas de retorno obrigatórias',xp:20,content:'<h3>Defeito em Massa</h3><p>Quando um fabricante descobre um defeito que pode causar risco, é obrigado a fazer <strong>recall</strong>: chamar todos os consumidores para reparo gratuito.</p><p>Exemplos famosos: airbags Takata (70 milhões de veículos), Samsung Galaxy Note 7 (bateria explosiva), brinquedos com peças que soltam.</p><p>O consumidor não paga nada no recall. Se não for notificado e sofrer dano, pode processar o fabricante por danos materiais e morais.</p>',q:'Quem paga pelo recall?',o:['O consumidor','O governo','O fabricante','A loja que vendeu'],c:2,exp:'O fabricante paga integralmente pelo recall. É sua responsabilidade corrigir defeitos de segurança sem custo algum para o consumidor.'},
    {title:'Consumo Consciente',sub:'Seus direitos incluem responsabilidade',xp:20,content:'<h3>Direitos e Deveres</h3><p>Ser consumidor consciente vai além de conhecer seus direitos. Inclui:</p><ul><li>Ler contratos antes de assinar</li><li>Pesquisar antes de comprar (evita frustrações)</li><li>Não abusar do direito de arrependimento</li><li>Reclamar de forma respeitosa e documentada</li></ul><p>Consumidores informados forçam empresas a melhorar. Quando você reclama de um produto ruim, está ajudando todos os futuros compradores. <em>Consumo consciente é um ato de cidadania.</em></p>',q:'Qual é o papel do consumidor consciente?',o:['Comprar sempre o mais barato','Nunca reclamar','Pesquisar, conhecer seus direitos e reclamar quando necessário','Boicotar todas as grandes empresas'],c:2,exp:'Consumidor consciente pesquisa, lê contratos, conhece seus direitos e reclama quando necessário. Isso melhora o mercado para todos.'}
  ]),
  generateModule('Como Funciona um Contrato','Contratos, acordos, cláusulas e o que assinar ou não assinar','📋','lavender','direito',[
    {title:'O que é um Contrato?',sub:'Acordo com força de lei',xp:20,content:'<h3>Contrato: Promessa com Consequências</h3><p>Um contrato é um <strong>acordo entre partes que gera obrigações legais</strong>. Pode ser escrito, verbal ou até implícito (quando você entra num ônibus, há um contrato de transporte).</p><p>Elementos essenciais: partes capazes, objeto lícito, forma adequada e consentimento livre. Se faltar qualquer um, o contrato pode ser anulado.</p><p>Contratos existem para dar <strong>segurança</strong>. Sem eles, nenhuma transação complexa seria possível — de alugar um apartamento a abrir uma empresa.</p>',q:'O que torna um contrato válido?',o:['Apenas a assinatura','Partes capazes, objeto lícito, forma adequada e consentimento','Registro em cartório','Presença de advogado'],c:1,exp:'Um contrato válido precisa de: partes capazes (maiores de idade, lúcidas), objeto lícito (legal), forma adequada e consentimento livre (sem coação). Registro em cartório é opcional na maioria dos casos.'},
    {title:'Tipos de Contrato',sub:'Aluguel, trabalho, prestação de serviço',xp:20,content:'<h3>Contratos do Dia a Dia</h3><p>Você já fez dezenas de contratos na vida, mesmo sem perceber:</p><ul><li><strong>Compra e venda</strong> — quando compra algo na loja</li><li><strong>Aluguel</strong> — contrato de locação de imóvel</li><li><strong>Trabalho</strong> — CLT ou prestação de serviço</li><li><strong>Streaming</strong> — Netflix, Spotify (contrato de adesão)</li><li><strong>Empréstimo</strong> — mútuo (dinheiro) ou comodato (coisas)</li></ul>',q:'Quando você assina Netflix, que tipo de contrato está fazendo?',o:['Contrato de trabalho','Contrato de compra e venda','Contrato de adesão','Contrato verbal'],c:2,exp:'Netflix, Spotify e serviços similares usam contratos de adesão: o consumidor aceita ou rejeita termos pré-definidos, sem poder negociar cláusulas individualmente.'},
    {title:'Cláusulas Importantes',sub:'O que olhar antes de assinar',xp:25,content:'<h3>Leia Antes de Assinar</h3><p>Cláusulas que você DEVE verificar em qualquer contrato:</p><ul><li><strong>Valor e forma de pagamento</strong> — juros, multas, reajustes</li><li><strong>Prazo</strong> — duração, renovação automática?</li><li><strong>Rescisão</strong> — como cancelar, multa por cancelamento</li><li><strong>Foro</strong> — onde resolver disputas</li></ul><p>Regra de ouro: <em>se não entendeu, não assine</em>. Peça para explicarem. Se pressionarem, desconfie.</p>',q:'O que fazer se não entender uma cláusula do contrato?',o:['Assinar e ver depois','Pedir explicação antes de assinar','Ignorar e assinar','Rasgar o contrato'],c:1,exp:'NUNCA assine o que não entende. Peça explicação, leve para casa, consulte alguém de confiança. Pressão para assinar rápido é bandeira vermelha.'},
    {title:'Multa por Cancelamento',sub:'Quando é justa e quando é abusiva',xp:25,content:'<h3>Quanto Custa Sair?</h3><p>Contratos com prazo mínimo (fidelidade) geralmente preveem multa por cancelamento antecipado. Mas há limites:</p><p>A multa deve ser <strong>proporcional</strong> ao tempo restante. Se faltam 3 de 12 meses, a multa deve ser 3/12 do valor, não 100%.</p><p>Telecoms (celular, internet) podem cobrar fidelidade máxima de 12 meses. Multas abusivas podem ser questionadas no Procon ou Juizado.</p>',q:'Como deve ser calculada a multa por cancelamento antecipado?',o:['Sempre 100% do contrato','Proporcional ao tempo restante','Decidida pela empresa','Não existe multa'],c:1,exp:'A multa deve ser proporcional ao tempo que falta para terminar o contrato. Cobrar 100% quando faltam poucos meses é abusivo e pode ser anulado judicialmente.'},
    {title:'Contrato de Aluguel',sub:'Direitos e deveres de inquilino e proprietário',xp:25,content:'<h3>Morando de Aluguel</h3><p>A Lei do Inquilinato (8.245/91) rege aluguéis no Brasil. Pontos-chave:</p><ul><li>Reajuste: uma vez por ano, pelo índice do contrato (geralmente IGPM ou IPCA)</li><li>Caução: máximo 3 meses de aluguel</li><li>Reparos: estruturais são do proprietário; uso diário são do inquilino</li><li>Prazo: contratos de 30+ meses dão direito de sair sem multa após esse prazo</li></ul>',q:'Quem paga reparos estruturais no imóvel alugado?',o:['O inquilino','O proprietário','Dividem igualmente','Depende do contrato'],c:1,exp:'A Lei do Inquilinato determina que reparos estruturais (telhado, encanamento principal, estrutura) são responsabilidade do PROPRIETÁRIO. Reparos de uso (torneira, lâmpada) são do inquilino.'},
    {title:'CLT: Contrato de Trabalho',sub:'Seus direitos como empregado',xp:25,content:'<h3>Trabalho com Carteira</h3><p>A CLT (Consolidação das Leis do Trabalho) é o contrato de trabalho mais comum no Brasil. Garante:</p><ul><li>Salário mínimo, 13º salário, férias + 1/3</li><li>FGTS (8% do salário depositado mensalmente)</li><li>Hora extra: +50% (dia útil), +100% (domingo/feriado)</li><li>Aviso prévio: 30 dias + 3 por ano trabalhado</li></ul><p>Na demissão sem justa causa, o empregado recebe: saldo de salário, férias proporcionais, 13º proporcional, multa de 40% do FGTS e pode sacar o FGTS.</p>',q:'Qual o adicional de hora extra em dia útil pela CLT?',o:['20%','30%','50%','100%'],c:2,exp:'A CLT determina adicional de 50% sobre a hora normal para horas extras em dias úteis. Em domingos e feriados, o adicional é de 100% (dobro).'},
    {title:'Contrato de Freelancer',sub:'PJ, MEI e prestação de serviço',xp:25,content:'<h3>Trabalho Sem Carteira</h3><p>Nem todo trabalho é CLT. Freelancers, MEIs e PJs usam contratos de prestação de serviço. Diferenças:</p><ul><li>Sem FGTS, 13º, férias remuneradas</li><li>Mais flexibilidade (horário, local)</li><li>Menos impostos (MEI: R$ 70/mês)</li><li>Sem vínculo empregatício</li></ul><p>Atenção: se há subordinação, horário fixo e exclusividade, é CLT disfarçada ("pejotização") — e é ilegal.</p>',q:'O que é "pejotização"?',o:['Abrir uma empresa legalmente','Disfarçar vínculo CLT como PJ para pagar menos','Terceirizar serviços','Trabalhar como freelancer'],c:1,exp:'Pejotização é quando a empresa obriga o trabalhador a abrir PJ para evitar encargos da CLT, mas mantém subordinação, horário fixo e exclusividade. É fraude trabalhista.'},
    {title:'Termos de Uso Online',sub:'O contrato que você nunca lê',xp:20,content:'<h3>Você Concordou com O Quê?</h3><p>Quando clica "Li e aceito os termos de uso", está assinando um contrato. A maioria das pessoas não lê — e as empresas sabem disso.</p><p>O que geralmente está lá: uso dos seus dados, propriedade do conteúdo que você posta, limitação de responsabilidade, foro de resolução (geralmente EUA).</p><p>Cláusulas abusivas continuam sendo nulas pelo CDC, mesmo online. Mas provar que não leu não é defesa — ao clicar "aceito", você se comprometeu.</p>',q:'Clicar "Li e aceito" tem validade jurídica?',o:['Não, só vale contrato em papel','Sim, é considerado aceite do contrato','Depende do navegador','Só vale se imprimir'],c:1,exp:'Sim, aceite digital (clicar em "Li e aceito") tem plena validade jurídica no Brasil desde o Marco Civil da Internet (2014). É equivalente a assinar um contrato.'},
    {title:'Distrato: Como Encerrar um Contrato',sub:'Rescisão, distrato e resolução',xp:20,content:'<h3>Querendo Sair?</h3><p>Formas de encerrar um contrato:</p><ul><li><strong>Término natural</strong> — o prazo acabou</li><li><strong>Distrato</strong> — acordo mútuo para encerrar</li><li><strong>Rescisão</strong> — uma parte encerra por descumprimento da outra</li><li><strong>Resolução</strong> — encerramento por evento imprevisível (força maior)</li></ul><p>A COVID-19 gerou milhares de resoluções contratuais: aluguéis, eventos, viagens. A lei permite renegociação quando circunstâncias mudam drasticamente.</p>',q:'O que é distrato?',o:['Cancelamento unilateral','Acordo mútuo para encerrar o contrato','Processo judicial','Renovação automática'],c:1,exp:'Distrato é o encerramento de um contrato por acordo entre as partes. Diferente da rescisão (uma parte encerra por culpa da outra), o distrato é consensual.'},
    {title:'Assinatura Digital',sub:'O futuro dos contratos',xp:20,content:'<h3>Contratos na Era Digital</h3><p>Assinatura digital tem a mesma validade da manuscrita no Brasil (MP 2.200/2001 e Lei 14.063/2020). Plataformas como DocuSign, Clicksign e Autentique são aceitas em juízo.</p><p>Tipos de assinatura eletrônica:</p><ul><li><strong>Simples</strong> — email + senha (baixo risco)</li><li><strong>Avançada</strong> — com verificação de identidade</li><li><strong>Qualificada</strong> — certificado digital ICP-Brasil (máxima segurança)</li></ul><p>Vantagens: rapidez, economia, rastreabilidade e validade em qualquer lugar do mundo.</p>',q:'Assinatura digital tem validade jurídica no Brasil?',o:['Não, só a manuscrita vale','Sim, desde 2001','Apenas para empresas','Apenas com reconhecimento de firma'],c:1,exp:'Sim, assinatura digital tem plena validade jurídica no Brasil desde a MP 2.200/2001. Não precisa de reconhecimento de firma ou cartório para valer.'}
  ])
];

// Combine all expansion modules
const allExpansion = [...expansionModules, amHistory1, amHistory2, ...remainingExpansion];

// Now generate remaining quick modules for: logica, midia, saude, artes (8 modules)
// Using compact format for space
const quickModules = [];

// LOGICA +2
quickModules.push(generateModule('Falácias e Manipulação','Identifique erros de raciocínio, propaganda e argumentos enganosos','🎭','coral','logica',
  ['Ad Hominem','Espantalho','Falso Dilema','Apelo à Autoridade','Apelo à Emoção','Escorregadia','Tu Quoque','Generalização Apressada','Viés de Confirmação','Propaganda e Manipulação'].map((t,i)=>{
    const topics = [
      {sub:'Atacar a pessoa em vez do argumento',content:'<h3>Ad Hominem</h3><p>A falácia <em>ad hominem</em> ocorre quando alguém ataca a pessoa que fez o argumento, em vez de atacar o argumento em si.</p><p>Exemplo: "Você não pode falar de economia porque não tem faculdade." O argumento pode ser válido independente de quem o fez.</p><p>Versões: ad hominem direto (insulto), circunstancial ("você diz isso porque é rico") e tu quoque ("você também faz isso").</p>',q:'O que é falácia ad hominem?',o:['Argumento baseado em fatos','Atacar a pessoa em vez do argumento','Usar exemplos demais','Falar muito alto'],c:1,exp:'Ad hominem ("contra o homem") ataca quem fala, não o que foi dito. Um argumento é válido ou inválido por sua lógica, não pela pessoa que o apresenta.'},
      {sub:'Distorcer o argumento alheio para atacá-lo',content:'<h3>Falácia do Espantalho</h3><p>O <strong>espantalho</strong> (straw man) acontece quando alguém distorce o argumento do oponente para algo mais fácil de atacar.</p><p>Exemplo: "Sou contra gastar demais no governo." → "Então você quer acabar com hospitais públicos?" A pessoa não disse isso — o oponente criou um "espantalho" para derrubar.</p><p>Como identificar: se a resposta parece exagerada ou distorcida, provavelmente é um espantalho.</p>',q:'O que é a falácia do espantalho?',o:['Usar dados falsos','Distorcer o argumento do oponente','Repetir o mesmo ponto','Falar sobre outro assunto'],c:1,exp:'Espantalho (straw man): criar uma versão distorcida e exagerada do argumento alheio para atacá-la. É mais fácil derrubar um espantalho do que o argumento real.'},
      {sub:'Apresentar apenas duas opções quando há mais',content:'<h3>Falso Dilema</h3><p>O falso dilema apresenta apenas duas opções extremas quando, na verdade, existem várias possibilidades.</p><p>Exemplo: "Ou você apoia 100% o governo ou é inimigo do país." Existem muitas posições entre apoio total e oposição total.</p><p>"Ou concorda comigo ou é ignorante" — essa pressão binária é uma ferramenta de manipulação comum na política e nas redes sociais.</p>',q:'O que é falso dilema?',o:['Mentir sobre os fatos','Apresentar só duas opções quando há mais','Não ter opinião','Concordar com todos'],c:1,exp:'Falso dilema (ou falsa dicotomia) é apresentar apenas duas opções extremas quando existem alternativas intermediárias. A realidade raramente é preto ou branco.'},
      {sub:'Usar famosos ou títulos como prova',content:'<h3>Apelo à Autoridade</h3><p>Citar uma autoridade pode ser válido — mas se torna falácia quando a autoridade não é especialista no assunto ou quando se usa o nome como prova definitiva.</p><p>Exemplos: "Einstein acreditava em Deus, logo Deus existe" (Einstein era físico, não teólogo). "O ator famoso recomenda este medicamento" (ator não é médico).</p><p>Ciência funciona por evidências, não por nomes. Até cientistas brilhantes erram fora de sua área.</p>',q:'Quando o apelo à autoridade é uma falácia?',o:['Sempre','Quando a autoridade não é especialista no assunto','Nunca','Quando é um professor'],c:1,exp:'O apelo à autoridade é falácia quando a pessoa citada não é especialista no tema discutido, ou quando seu nome é usado como "prova" definitiva sem apresentar evidências.'},
      {sub:'Usar sentimentos em vez de lógica',content:'<h3>Apelo à Emoção</h3><p>O apelo emocional substitui argumentos racionais por sentimentos: medo, piedade, raiva ou orgulho.</p><p>Exemplo: "Pense nas crianças!" — usado para silenciar debate. Válido para motivar, mas não como argumento lógico.</p><p>Propaganda política e comercial usam emoção o tempo todo. Quando sentir forte emoção diante de um argumento, pare e pergunte: <em>qual é a evidência?</em></p>',q:'Qual o problema do apelo à emoção em debates?',o:['Emoções são proibidas','Substitui evidências por sentimentos','É sempre falso','Só funciona com crianças'],c:1,exp:'O apelo à emoção se torna falácia quando sentimentos substituem evidências e lógica. Emoções motivam ação, mas não provam verdade.'},
      {sub:'Se A acontecer, Z vai acontecer (sem provar)',content:'<h3>Ladeira Escorregadia</h3><p>A falácia da ladeira escorregadia (slippery slope) afirma que um pequeno passo levará inevitavelmente a consequências extremas, sem provar os passos intermediários.</p><p>Exemplo: "Se permitirmos X, logo vai acontecer Y, depois Z, e será o caos!" Cada passo precisa ser demonstrado separadamente.</p><p>Às vezes a cadeia é real. Mas frequentemente é exagero para criar medo e impedir qualquer mudança.</p>',q:'O que é a ladeira escorregadia?',o:['Um argumento sobre geografia','Afirmar que um passo levará a extremos sem provar os intermediários','Uma técnica de negociação','Um tipo de gráfico'],c:1,exp:'Ladeira escorregadia: argumentar que A inevitavelmente leva a Z (extremo), sem demonstrar os passos intermediários. Cada consequência precisa ser provada separadamente.'},
      {sub:'Apontar hipocrisia para invalidar o argumento',content:'<h3>Tu Quoque</h3><p>"Tu quoque" (você também) é apontar que a pessoa faz o que critica, como se isso invalidasse o argumento.</p><p>Exemplo: "Você fuma e me fala pra não fumar?" — o fato de a pessoa fumar não torna falso que fumar faz mal. O argumento continua válido.</p><p>Hipocrisia é um defeito moral, mas não destrói a lógica do argumento. Verdades permanecem verdades independente de quem as diz.</p>',q:'A hipocrisia de alguém invalida seu argumento?',o:['Sim, sempre','Não — o argumento pode ser válido mesmo que a pessoa seja hipócrita','Depende do assunto','Sim, se for político'],c:1,exp:'Tu quoque: apontar hipocrisia não invalida o argumento. "Médico fumante dizendo que fumar faz mal" — continua verdade. Avalie o argumento, não a pessoa.'},
      {sub:'Conclusões baseadas em poucos casos',content:'<h3>Generalização Apressada</h3><p>Tirar conclusões gerais a partir de poucos exemplos ou experiências pessoais.</p><p>Exemplos: "Conheci dois franceses rudes, logo franceses são rudes." "Meu avô fumou até 90 anos, logo fumar não faz mal."</p><p>Anedota não é dado. Para generalizar, precisamos de amostras grandes e representativas. Ciência usa estatística justamente para evitar essa falácia.</p>',q:'O que é generalização apressada?',o:['Usar muitos dados','Tirar conclusão geral de poucos exemplos','Demorar para concluir','Citar pesquisas científicas'],c:1,exp:'Generalização apressada: concluir uma regra geral a partir de poucos casos. É preciso amostra grande e representativa para generalizar com segurança.'},
      {sub:'Buscar apenas o que confirma sua opinião',content:'<h3>Viés de Confirmação</h3><p>O viés de confirmação é a tendência de buscar, interpretar e lembrar informações que <strong>confirmam</strong> o que já acreditamos, ignorando o que contradiz.</p><p>Redes sociais amplificam isso: algoritmos mostram mais do que você já gosta. Resultado: bolhas de opinião onde todos concordam entre si.</p><p>Antídoto: busque ativamente opiniões contrárias. Leia argumentos do "outro lado". Se sua opinião não sobrevive ao melhor argumento contrário, talvez precise revisá-la.</p>',q:'O que é viés de confirmação?',o:['Confirmar dados científicos','Buscar apenas informações que confirmam o que já acreditamos','Verificar fontes','Mudar de opinião frequentemente'],c:1,exp:'Viés de confirmação: tendência inconsciente de buscar e valorizar informações que reforçam nossas crenças, ignorando evidências contrárias. Todo mundo tem — reconhecê-lo é o primeiro passo.'},
      {sub:'Técnicas de manipulação em massa',content:'<h3>A Arte da Propaganda</h3><p>Edward Bernays (sobrinho de Freud) criou a propaganda moderna nos anos 1920. Técnicas que ele inventou são usadas até hoje:</p><ul><li><strong>Repetição</strong> — repita algo bastante e parecerá verdade</li><li><strong>Associação</strong> — conecte produto/ideia a emoções positivas</li><li><strong>Bandwagon</strong> — "todo mundo está fazendo"</li><li><strong>Medo</strong> — crie uma ameaça e ofereça a solução</li></ul><p>Saber identificar essas técnicas é a melhor defesa. Quando perceber uma sendo usada em você, pare e pense: <em>estão apelando para minha razão ou para minha emoção?</em></p>',q:'Qual técnica de propaganda repete uma mensagem até parecer verdade?',o:['Associação','Bandwagon','Repetição (Illusory Truth Effect)','Medo'],c:2,exp:'O "efeito de verdade ilusória" (illusory truth effect) mostra que informações repetidas parecem mais verdadeiras, mesmo que sejam falsas. Propagandas e fake news exploram isso.'}
    ];
    return {...topics[i],title:t,xp:[25,25,25,25,20,25,20,20,25,30][i]};
  })
));

// Save all modules
const allNew = [...allExpansion, ...quickModules];

console.log(`Generating ${allNew.length} modules (${allNew.reduce((s,m)=>s+m.lessons.length,0)} lessons)...`);

// Add to index (without content, only metadata + quizzes)
allNew.forEach((mod, i) => {
  const idx = startIdx + i;

  // Index entry (no content)
  const indexEntry = {
    title: mod.title,
    desc: mod.desc,
    icon: mod.icon,
    color: mod.color,
    discipline: mod.discipline,
    lessons: mod.lessons.map(l => ({
      title: l.title,
      sub: l.sub,
      xp: l.xp,
      quiz: l.quiz
    }))
  };
  index.push(indexEntry);

  // Full module file (with content)
  const fullMod = {
    title: mod.title,
    desc: mod.desc,
    icon: mod.icon,
    color: mod.color,
    discipline: mod.discipline,
    lessons: mod.lessons
  };
  fs.writeFileSync(path.join(LESSONS_DIR, `mod-${idx}.json`), JSON.stringify(fullMod));
  console.log(`  ✓ mod-${idx}.json — ${mod.title} (${mod.lessons.length} lessons)`);
});

// Save updated index
fs.writeFileSync(INDEX_PATH, JSON.stringify(index));
console.log(`\nIndex updated: ${index.length} modules total`);
console.log(`Total lessons: ${index.reduce((s,m)=>s+m.lessons.length,0)}`);
